[package]
name = "mpc-snarks"
version = "0.1.0"
authors = ["Alex Ozdemir <aozdemir@hmc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = { path = "../algebra/ff", version = "0.2.0", default-features = false }
ark-bls12-377 = { path = "../curves/bls12_377", version = "0.2.0", default-features = false, features = ["curve"] }
ark-ec = { path = "../algebra/ec", version = "0.2.0", default-features = false }
ark-poly = { path = "../algebra/poly", version = "0.2.0", default-features = false }
ark-relations = { path = "../snark/relations", version = "0.2.0", default-features = false }
ark-serialize = { path = "../algebra/serialize", version = "0.2.0", default-features = false, features = [ "derive" ] }
ark-std = { path = "../utils", default-features = false, features = [ "print-trace" ] }
ark-groth16 = { path = "../groth16", version = "0.2.0", default-features = false, features = [ "std" ] }
ark-marlin = { path = "../marlin", version = "0.2.0", default-features = false, features = [ "std" ] }
ark-poly-commit = { path = "../poly-commit", version = "0.2.0", default-features = false, features = [ "std" ] }
lazy_static = "1"
derivative = { version = "2.0", features = ["use_core"]}
log = {version = "0.4"}
digest = { version = "0.9" }

rand = { version = "0.7", default-features = false }
rand_chacha = { version = "0.3", default-features = false }
rayon = { version = "1", optional = true }
zeroize = { version = "1", default-features = false, features = ["zeroize_derive"] }

mpc-net = { path = "../mpc-net" }
mpc-trait = { path = "../mpc-trait" }
mpc-algebra = { path = "../mpc-algebra" }
mpc-plonk = { path = "../mpc-plonk" }

env_logger = "0.8"
structopt = "0.3"
clap = "2"
merlin = "3"
sha2 = "0.9"
blake2 = "0.9"

[features]
default = ["std", "parallel"]
std = ["ark-ec/std", "ark-ff/std", "ark-poly/std", "ark-std/std", "ark-poly-commit/std"]
parallel = [ "rayon", "ark-ec/parallel", "ark-ff/parallel", "ark-poly/parallel", "ark-std/parallel", "ark-poly-commit/parallel" ]

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "proof"
path = "src/proof.rs"

[profile.release]
debug = true
